# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  encoding: unicode

development:
   adapter: postgresql
   encoding: unicode
   database: job_board_develop
   username: esraa
   password: esraa123

test:
   adapter: postgresql
   encoding: unicode
   database: job_board_test
   username: esraa
   password: esraa123
 
production:
   adapter: postgresql
   encoding: unicode
   database: job_board_production
   username: esraa
   password: esraa123
